//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVMH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVMH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7	0.27	0.36	20.7	0.045	45	170	1.001	3	0.45	8.8	6
        ///6.3	0.3	0.34	1.6	0.049	14	132	0.994	3.3	0.49	9.5	6
        ///8.1	0.28	0.4	6.9	0.05	30	97	0.9951	3.26	0.44	10.1	6
        ///7.2	0.23	0.32	8.5	0.058	47	186	0.9956	3.19	0.4	9.9	6
        ///7.2	0.23	0.32	8.5	0.058	47	186	0.9956	3.19	0.4	9.9	6
        ///8.1	0.28	0.4	6.9	0.05	30	97	0.9951	3.26	0.44	10.1	6
        ///6.2	0.32	0.16	7	0.045	30	136	0.9949	3.18	0.47	9.6	6
        ///7	0.27	0.36	20.7	0.045	45	170	1.001	3	0.45	8.8	6
        ///6.3	0.3	0.34	1.6	0.049	14	132	0.994	3.3	0.49	9.5	6
        ///8.1	0.22	0.43	1.5	0.044	28	129	0.9938	3.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ruou {
            get {
                return ResourceManager.GetString("Ruou", resourceCulture);
            }
        }
    }
}
